server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Fix Angular routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api calls to your backend
    location /api/ {
        proxy_pass https://mom2be-244972601130.asia-south1.run.app/;
        proxy_set_header Host mom2be-244972601130.asia-south1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
