import { Injectable } from '@angular/core';

type Language = 'english' | 'kannada' | 'hindi' | 'urdu';

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  private readonly translations: Record<Language, Record<string, string>> = {
    english: {
      appName: 'Mom2Be',
      appSubtitle: 'Pregnancy Care Companion',
      selectLanguage: 'Select Language',
      kannada: 'Kannada',
      hindi: 'Hindi',
      urdu: 'Urdu',
      english: 'English',
      registration: 'Registration',
      motherName: 'Mother Name',
      lmpDate: 'LMP Date',
      language: 'Language',
      phone: 'Phone',
      husbandPhone: 'Husband Phone',
      ashaWorker: 'ASHA Worker',
      anganwadiName: 'Anganwadi Name',
      anganwadiPhone: 'Anganwadi Phone',
      email: 'Email',
      register: 'Register',
      symptoms: 'Symptoms',
      chat: 'Chat',
      medicine: 'Medicine',
      schemes: 'Schemes',
      history: 'History',
      injection: 'Injection',
      anganwadi: 'Anganwadi',
      symptomChecker: 'Symptom Checker',
      describeSymptoms: 'Describe your symptoms...',
      analyzeSymptoms: 'Analyze Symptoms',
      riskLevel: 'Risk Level',
      analysisComplete: 'Analysis complete.',
      send: 'Send',
      typeMessage: 'Type your message...',
      loading: 'Loading...',
      pageContentPlaceholder: 'This page content will be available soon.',
      risk_high: 'High',
      risk_medium: 'Medium',
      risk_low: 'Low',
      welcomeEyebrow: 'Mom2Be AI Companion',
      welcomeTitle: 'Warm, supportive pregnancy care for every mother.',
      welcomeDescription: 'Start in the mother\'s language, make important updates easy to understand, and support every week with a home screen that feels calm, friendly, and caring.',
      heroChipGuidance: 'Simple AI guidance',
      heroChipAlerts: 'Easy-to-read alerts',
      heroChipSupport: 'Week-by-week support',
      legendHighDesc: 'Immediate attention',
      legendMediumDesc: 'Watch closely',
      legendLowDesc: 'Gentle guidance',
      welcomeSpeech: 'Hello mama, let\'s start your care journey.',
      dailyTip: 'Daily Tip',
      hydrationReminderReady: 'Hydration reminder ready',
      careView: 'Care View',
      importantUpdatesClear: 'Important updates stay clear',
      step1: 'Step 1',
      languagePanelDescription: 'Choose the language that should shape the full Mom2Be journey from registration to reminders.',
      languageCaptionKannada: 'Local care guidance',
      languageCaptionHindi: 'Easy onboarding',
      languageCaptionUrdu: 'Inclusive support',
      languageCaptionEnglish: 'Comfortable start',
      registerEyebrow: 'Registration',
      registerHeroTitle: 'Create a profile that powers personalized care.',
      registerHeroDescription: 'A simple setup unlocks reminders, local support, and personalized guidance for the full pregnancy journey.',
      registerBenefitLocalizedTitle: 'Support in your language',
      registerBenefitLocalizedDesc: 'The full experience follows your chosen language.',
      registerBenefitAlertTitle: 'Clear alerts',
      registerBenefitAlertDesc: 'Important updates remain easy to notice and understand.',
      registerBenefitContactTitle: 'Support contacts ready',
      registerBenefitContactDesc: 'Add family, ASHA, and Anganwadi details in one place.',
      registerBubble: 'Personalized care starts with a few simple details.',
      registerSetup: 'Setup',
      registerSetupDesc: 'Ready in under a minute',
      registerJourney: 'Journey',
      registerJourneyDesc: 'Registration to reminders in one flow',
      step2: 'Step 2',
      quickSetup: 'Quick setup',
      motherNamePlaceholder: 'Enter the mother\'s name',
      lmpDateHint: 'Choose the date of the last menstrual period.',
      languageLockedHint: 'The selected language appears here automatically.',
      phonePlaceholder: 'Enter phone number',
      husbandPhonePlaceholder: 'Enter husband\'s phone number',
      ashaWorkerPlaceholder: 'Enter ASHA worker name',
      anganwadiNamePlaceholder: 'Enter Anganwadi center name',
      anganwadiPhonePlaceholder: 'Enter Anganwadi phone number',
      emailPlaceholder: 'Enter email address',
      footerNote: 'Your profile helps Mom2Be tailor reminders, symptom guidance, and support contacts.'
    },
    kannada: {
      appName: 'Mom2Be',
      appSubtitle: 'ಗರ್ಭಧಾರಣೆ ಆರೈಕೆ ಸಂಗಾತಿ',
      selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      kannada: 'ಕನ್ನಡ',
      hindi: 'ಹಿಂದಿ',
      urdu: 'ಉರ್ದು',
      english: 'ಇಂಗ್ಲಿಷ್',
      registration: 'ನೋಂದಣಿ',
      motherName: 'ತಾಯಿಯ ಹೆಸರು',
      lmpDate: 'ಕೊನೆಯ ಮಾಸಿಕ ದಿನಾಂಕ',
      language: 'ಭಾಷೆ',
      phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
      husbandPhone: 'ಗಂಡನ ಫೋನ್ ಸಂಖ್ಯೆ',
      ashaWorker: 'ಆಶಾ ಕಾರ್ಯಕರ್ತೆ',
      anganwadiName: 'ಅಂಗನವಾಡಿ ಹೆಸರು',
      anganwadiPhone: 'ಅಂಗನವಾಡಿ ಫೋನ್ ಸಂಖ್ಯೆ',
      email: 'ಇಮೇಲ್',
      register: 'ನೋಂದಾಯಿಸಿ',
      symptoms: 'ಲಕ್ಷಣಗಳು',
      chat: 'ಚಾಟ್',
      medicine: 'ಔಷಧಿ',
      schemes: 'ಯೋಜನೆಗಳು',
      history: 'ಇತಿಹಾಸ',
      injection: 'ಇಂಜೆಕ್ಷನ್',
      anganwadi: 'ಅಂಗನವಾಡಿ',
      symptomChecker: 'ಲಕ್ಷಣ ಪರಿಶೀಲನೆ',
      describeSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ...',
      analyzeSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
      riskLevel: 'ಅಪಾಯದ ಮಟ್ಟ',
      analysisComplete: 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ.',
      send: 'ಕಳುಹಿಸಿ',
      typeMessage: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      pageContentPlaceholder: 'ಈ ಪುಟದ ವಿಷಯ ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಾಗುತ್ತದೆ.',
      risk_high: 'ಹೆಚ್ಚು',
      risk_medium: 'ಮಧ್ಯಮ',
      risk_low: 'ಕಡಿಮೆ',
      welcomeEyebrow: 'Mom2Be AI ಸಂಗಾತಿ',
      welcomeTitle: 'ಪ್ರತಿಯೊಬ್ಬ ತಾಯಿಗಾಗಿ ಆತ್ಮೀಯ ಮತ್ತು ಬೆಂಬಲಕಾರಿ ಗರ್ಭಧಾರಣೆ ಆರೈಕೆ.',
      welcomeDescription: 'ತಾಯಿಯ ಭಾಷೆಯಲ್ಲಿ ಆರಂಭಿಸಿ, ಮುಖ್ಯ ಮಾಹಿತಿಯನ್ನು ಸುಲಭವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ಮತ್ತು ಪ್ರತೀ ವಾರದ ಸಹಾಯವನ್ನು ಶಾಂತ ಹಾಗೂ ಸ್ನೇಹಪೂರ್ಣ ಮುಖಪುಟದಲ್ಲಿ ಪಡೆಯಿರಿ.',
      heroChipGuidance: 'ಸರಳ AI ಮಾರ್ಗದರ್ಶನ',
      heroChipAlerts: 'ಸುಲಭವಾಗಿ ಓದುವ ಎಚ್ಚರಿಕೆಗಳು',
      heroChipSupport: 'ವಾರವಾರದ ಬೆಂಬಲ',
      legendHighDesc: 'ತಕ್ಷಣ ಗಮನ',
      legendMediumDesc: 'ಗಮನಿಸಿ',
      legendLowDesc: 'ಸೌಮ್ಯ ಮಾರ್ಗದರ್ಶನ',
      welcomeSpeech: 'ನಮಸ್ಕಾರ ಅಮ್ಮಾ, ನಿಮ್ಮ ಆರೈಕೆ ಪ್ರಯಾಣವನ್ನು ಆರಂಭಿಸೋಣ.',
      dailyTip: 'ದಿನದ ಸಲಹೆ',
      hydrationReminderReady: 'ನೀರು ಕುಡಿಯುವ ನೆನಪು ಸಿದ್ಧವಾಗಿದೆ',
      careView: 'ಆರೈಕೆ ದೃಶ್ಯ',
      importantUpdatesClear: 'ಮುಖ್ಯ ಮಾಹಿತಿಗಳು ಸ್ಪಷ್ಟವಾಗಿರುತ್ತವೆ',
      step1: 'ಹಂತ 1',
      languagePanelDescription: 'ನೋಂದಣಿಯಿಂದ ನೆನಪುಗಳವರೆಗೆ Mom2Be ಅನುಭವವನ್ನು ರೂಪಿಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
      languageCaptionKannada: 'ಸ್ಥಳೀಯ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶನ',
      languageCaptionHindi: 'ಸುಲಭ ಆರಂಭ',
      languageCaptionUrdu: 'ಎಲ್ಲರಿಗೂ ಒಳಗೊಂಡ ಸಹಾಯ',
      languageCaptionEnglish: 'ಆರಾಮದಾಯಕ ಆರಂಭ',
      registerEyebrow: 'ನೋಂದಣಿ',
      registerHeroTitle: 'ವೈಯಕ್ತಿಕ ಆರೈಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸುವ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ.',
      registerHeroDescription: 'ಒಂದು ಸರಳ ಸೆಟಪ್ ಮೂಲಕ ನೆನಪುಗಳು, ಸ್ಥಳೀಯ ಬೆಂಬಲ ಮತ್ತು ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನ ಸಿಗುತ್ತದೆ.',
      registerBenefitLocalizedTitle: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಬೆಂಬಲ',
      registerBenefitLocalizedDesc: 'ಆಯ್ಕೆ ಮಾಡಿದ ಭಾಷೆಯಲ್ಲಿ ಸಂಪೂರ್ಣ ಅನುಭವ.',
      registerBenefitAlertTitle: 'ಸ್ಪಷ್ಟ ಎಚ್ಚರಿಕೆಗಳು',
      registerBenefitAlertDesc: 'ಮುಖ್ಯ ಮಾಹಿತಿಗಳು ಸುಲಭವಾಗಿ ಕಾಣುತ್ತವೆ.',
      registerBenefitContactTitle: 'ಸಹಾಯ ಸಂಪರ್ಕಗಳು ಸಿದ್ಧ',
      registerBenefitContactDesc: 'ಕುಟುಂಬ, ಆಶಾ ಮತ್ತು ಅಂಗನವಾಡಿ ವಿವರಗಳನ್ನು ಒಂದೇ ಜಾಗದಲ್ಲಿ ಸೇರಿಸಿ.',
      registerBubble: 'ಕೆಲವೇ ವಿವರಗಳಿಂದ ವೈಯಕ್ತಿಕ ಆರೈಕೆ ಆರಂಭವಾಗುತ್ತದೆ.',
      registerSetup: 'ಸೆಟಪ್',
      registerSetupDesc: 'ಒಂದು ನಿಮಿಷಕ್ಕಿಂತ ಕಡಿಮೆ ಸಮಯ',
      registerJourney: 'ಪ್ರಯಾಣ',
      registerJourneyDesc: 'ನೋಂದಣಿಯಿಂದ ನೆನಪುಗಳವರೆಗೆ ಒಂದೇ ಹರಿವು',
      step2: 'ಹಂತ 2',
      quickSetup: 'ತ್ವರಿತ ಸೆಟಪ್',
      motherNamePlaceholder: 'ತಾಯಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      lmpDateHint: 'ಕೊನೆಯ ಮಾಸಿಕ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
      languageLockedHint: 'ಆಯ್ಕೆ ಮಾಡಿದ ಭಾಷೆ ಇಲ್ಲಿ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕಾಣಿಸುತ್ತದೆ.',
      phonePlaceholder: 'ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      husbandPhonePlaceholder: 'ಗಂಡನ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      ashaWorkerPlaceholder: 'ಆಶಾ ಕಾರ್ಯಕರ್ತೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      anganwadiNamePlaceholder: 'ಅಂಗನವಾಡಿ ಕೇಂದ್ರದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      anganwadiPhonePlaceholder: 'ಅಂಗನವಾಡಿ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      emailPlaceholder: 'ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
      footerNote: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ Mom2Be ಗೆ ನೆನಪುಗಳು, ಲಕ್ಷಣ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಸಹಾಯ ಸಂಪರ್ಕಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.'
    },
    hindi: {
      appName: 'Mom2Be',
      appSubtitle: 'गर्भावस्था देखभाल साथी',
      selectLanguage: 'भाषा चुनें',
      kannada: 'कन्नड़',
      hindi: 'हिंदी',
      urdu: 'उर्दू',
      english: 'अंग्रेज़ी',
      registration: 'पंजीकरण',
      motherName: 'माँ का नाम',
      lmpDate: 'अंतिम माहवारी तिथि',
      language: 'भाषा',
      phone: 'फोन नंबर',
      husbandPhone: 'पति का फोन नंबर',
      ashaWorker: 'आशा कार्यकर्ता',
      anganwadiName: 'आंगनवाड़ी का नाम',
      anganwadiPhone: 'आंगनवाड़ी फोन नंबर',
      email: 'ईमेल',
      register: 'पंजीकरण करें',
      symptoms: 'लक्षण',
      chat: 'चैट',
      medicine: 'दवा',
      schemes: 'योजनाएँ',
      history: 'इतिहास',
      injection: 'इंजेक्शन',
      anganwadi: 'आंगनवाड़ी',
      symptomChecker: 'लक्षण जाँच',
      describeSymptoms: 'अपने लक्षण लिखें...',
      analyzeSymptoms: 'लक्षण जाँचें',
      riskLevel: 'जोखिम स्तर',
      analysisComplete: 'विश्लेषण पूरा हुआ।',
      send: 'भेजें',
      typeMessage: 'अपना संदेश लिखें...',
      loading: 'लोड हो रहा है...',
      pageContentPlaceholder: 'इस पेज की सामग्री जल्द उपलब्ध होगी।',
      risk_high: 'उच्च',
      risk_medium: 'मध्यम',
      risk_low: 'कम',
      welcomeEyebrow: 'Mom2Be AI साथी',
      welcomeTitle: 'हर माँ के लिए स्नेहपूर्ण और सहायक गर्भावस्था देखभाल।',
      welcomeDescription: 'माँ की भाषा में शुरुआत करें, ज़रूरी जानकारी आसानी से समझें, और हर हफ्ते की मदद एक शांत और अपनापन देने वाले होम पेज पर पाएँ।',
      heroChipGuidance: 'सरल AI मार्गदर्शन',
      heroChipAlerts: 'आसानी से पढ़े जाने वाले अलर्ट',
      heroChipSupport: 'हफ्ता-दर-हफ्ता साथ',
      legendHighDesc: 'तुरंत ध्यान',
      legendMediumDesc: 'ध्यान से देखें',
      legendLowDesc: 'हल्का मार्गदर्शन',
      welcomeSpeech: 'नमस्ते माँ, चलिए आपकी देखभाल की यात्रा शुरू करें।',
      dailyTip: 'आज की सलाह',
      hydrationReminderReady: 'पानी पीने की याद तैयार है',
      careView: 'देखभाल दृश्य',
      importantUpdatesClear: 'ज़रूरी जानकारी साफ दिखाई देगी',
      step1: 'चरण 1',
      languagePanelDescription: 'वह भाषा चुनें जो पंजीकरण से लेकर रिमाइंडर तक पूरे Mom2Be अनुभव को तय करे।',
      languageCaptionKannada: 'स्थानीय देखभाल मार्गदर्शन',
      languageCaptionHindi: 'आसान शुरुआत',
      languageCaptionUrdu: 'सबके लिए सहायक',
      languageCaptionEnglish: 'आरामदायक शुरुआत',
      registerEyebrow: 'पंजीकरण',
      registerHeroTitle: 'ऐसा प्रोफ़ाइल बनाएँ जो व्यक्तिगत देखभाल शुरू करे।',
      registerHeroDescription: 'एक आसान सेटअप से रिमाइंडर, स्थानीय सहायता और व्यक्तिगत मार्गदर्शन मिलता है।',
      registerBenefitLocalizedTitle: 'आपकी भाषा में सहायता',
      registerBenefitLocalizedDesc: 'चुनी हुई भाषा में पूरा अनुभव।',
      registerBenefitAlertTitle: 'साफ और समझने योग्य अलर्ट',
      registerBenefitAlertDesc: 'ज़रूरी जानकारी तुरंत नज़र आएगी।',
      registerBenefitContactTitle: 'सहायता संपर्क तैयार',
      registerBenefitContactDesc: 'परिवार, आशा और आंगनवाड़ी की जानकारी एक जगह जोड़ें।',
      registerBubble: 'कुछ आसान जानकारियों से व्यक्तिगत देखभाल शुरू होती है।',
      registerSetup: 'सेटअप',
      registerSetupDesc: 'एक मिनट से कम समय में',
      registerJourney: 'यात्रा',
      registerJourneyDesc: 'पंजीकरण से रिमाइंडर तक एक ही प्रवाह',
      step2: 'चरण 2',
      quickSetup: 'त्वरित सेटअप',
      motherNamePlaceholder: 'माँ का नाम लिखें',
      lmpDateHint: 'अंतिम माहवारी की तारीख चुनें।',
      languageLockedHint: 'चुनी हुई भाषा यहाँ अपने आप दिखेगी।',
      phonePlaceholder: 'फोन नंबर लिखें',
      husbandPhonePlaceholder: 'पति का फोन नंबर लिखें',
      ashaWorkerPlaceholder: 'आशा कार्यकर्ता का नाम लिखें',
      anganwadiNamePlaceholder: 'आंगनवाड़ी केंद्र का नाम लिखें',
      anganwadiPhonePlaceholder: 'आंगनवाड़ी फोन नंबर लिखें',
      emailPlaceholder: 'ईमेल पता लिखें',
      footerNote: 'आपका प्रोफ़ाइल Mom2Be को रिमाइंडर, लक्षण मार्गदर्शन और सहायता संपर्कों को बेहतर ढंग से व्यक्तिगत बनाने में मदद करता है।'
    },
    urdu: {
      appName: 'Mom2Be',
      appSubtitle: 'حمل کی دیکھ بھال کا ساتھی',
      selectLanguage: 'زبان منتخب کریں',
      kannada: 'کنڑ',
      hindi: 'ہندی',
      urdu: 'اردو',
      english: 'انگریزی',
      registration: 'رجسٹریشن',
      motherName: 'ماں کا نام',
      lmpDate: 'آخری ماہواری کی تاریخ',
      language: 'زبان',
      phone: 'فون نمبر',
      husbandPhone: 'شوہر کا فون نمبر',
      ashaWorker: 'آشا ورکر',
      anganwadiName: 'آنگن واڑی کا نام',
      anganwadiPhone: 'آنگن واڑی فون نمبر',
      email: 'ای میل',
      register: 'رجسٹر کریں',
      symptoms: 'علامات',
      chat: 'چیٹ',
      medicine: 'دوا',
      schemes: 'اسکیمیں',
      history: 'ریکارڈ',
      injection: 'انجکشن',
      anganwadi: 'آنگن واڑی',
      symptomChecker: 'علامات کی جانچ',
      describeSymptoms: 'اپنی علامات لکھیں...',
      analyzeSymptoms: 'علامات جانچیں',
      riskLevel: 'خطرے کی سطح',
      analysisComplete: 'تجزیہ مکمل ہوا۔',
      send: 'بھیجیں',
      typeMessage: 'اپنا پیغام لکھیں...',
      loading: 'لوڈ ہو رہا ہے...',
      pageContentPlaceholder: 'اس صفحے کا مواد جلد دستیاب ہوگا۔',
      risk_high: 'زیادہ',
      risk_medium: 'درمیانہ',
      risk_low: 'کم',
      welcomeEyebrow: 'Mom2Be AI ساتھی',
      welcomeTitle: 'ہر ماں کے لیے پُرسکون اور مددگار حمل کی دیکھ بھال۔',
      welcomeDescription: 'ماں کی زبان میں آغاز کریں، اہم معلومات آسانی سے سمجھیں، اور ہر ہفتے کی مدد ایک نرم اور دوستانہ ہوم پیج پر پائیں۔',
      heroChipGuidance: 'آسان AI رہنمائی',
      heroChipAlerts: 'آسانی سے پڑھے جانے والے الرٹس',
      heroChipSupport: 'ہفتہ وار مدد',
      legendHighDesc: 'فوراً توجہ',
      legendMediumDesc: 'غور سے دیکھیں',
      legendLowDesc: 'نرم رہنمائی',
      welcomeSpeech: 'السلام علیکم اماں، آئیے آپ کی دیکھ بھال کا سفر شروع کریں۔',
      dailyTip: 'آج کا مشورہ',
      hydrationReminderReady: 'پانی پینے کی یاد دہانی تیار ہے',
      careView: 'نگہداشت منظر',
      importantUpdatesClear: 'اہم معلومات صاف نظر آئیں گی',
      step1: 'مرحلہ 1',
      languagePanelDescription: 'وہ زبان منتخب کریں جو رجسٹریشن سے لے کر یاد دہانیوں تک پورے Mom2Be تجربے کو بنائے۔',
      languageCaptionKannada: 'مقامی نگہداشت رہنمائی',
      languageCaptionHindi: 'آسان آغاز',
      languageCaptionUrdu: 'سب کے لیے مددگار',
      languageCaptionEnglish: 'آرام دہ آغاز',
      registerEyebrow: 'رجسٹریشن',
      registerHeroTitle: 'ایسا پروفائل بنائیں جو ذاتی نگہداشت شروع کرے۔',
      registerHeroDescription: 'ایک آسان سیٹ اپ سے یاد دہانیاں، مقامی مدد اور ذاتی رہنمائی حاصل ہوتی ہے۔',
      registerBenefitLocalizedTitle: 'آپ کی زبان میں مدد',
      registerBenefitLocalizedDesc: 'منتخب زبان میں مکمل تجربہ۔',
      registerBenefitAlertTitle: 'صاف اور سمجھنے والے الرٹس',
      registerBenefitAlertDesc: 'اہم معلومات فوراً نمایاں رہتی ہیں۔',
      registerBenefitContactTitle: 'مدد کے رابطے تیار',
      registerBenefitContactDesc: 'خاندان، آشا اور آنگن واڑی کی تفصیل ایک جگہ شامل کریں۔',
      registerBubble: 'چند آسان معلومات سے ذاتی نگہداشت شروع ہوتی ہے۔',
      registerSetup: 'سیٹ اپ',
      registerSetupDesc: 'ایک منٹ سے بھی کم وقت',
      registerJourney: 'سفر',
      registerJourneyDesc: 'رجسٹریشن سے یاد دہانیوں تک ایک ہی بہاؤ',
      step2: 'مرحلہ 2',
      quickSetup: 'فوری سیٹ اپ',
      motherNamePlaceholder: 'ماں کا نام لکھیں',
      lmpDateHint: 'آخری ماہواری کی تاریخ منتخب کریں۔',
      languageLockedHint: 'منتخب زبان یہاں خود بخود نظر آئے گی۔',
      phonePlaceholder: 'فون نمبر لکھیں',
      husbandPhonePlaceholder: 'شوہر کا فون نمبر لکھیں',
      ashaWorkerPlaceholder: 'آشا ورکر کا نام لکھیں',
      anganwadiNamePlaceholder: 'آنگن واڑی مرکز کا نام لکھیں',
      anganwadiPhonePlaceholder: 'آنگن واڑی فون نمبر لکھیں',
      emailPlaceholder: 'ای میل پتہ لکھیں',
      footerNote: 'آپ کا پروفائل Mom2Be کو یاد دہانیوں، علامات کی رہنمائی اور مدد کے رابطوں کو بہتر طور پر ذاتی بنانے میں مدد دیتا ہے۔'
    }
  };

  normalizeLanguage(language: string | null | undefined): Language {
    switch ((language || '').toLowerCase()) {
      case 'kn':
      case 'kannada':
        return 'kannada';
      case 'hi':
      case 'hindi':
        return 'hindi';
      case 'ur':
      case 'urdu':
        return 'urdu';
      default:
        return 'english';
    }
  }

  setLanguage(language: string): void {
    const normalized = this.normalizeLanguage(language);
    localStorage.setItem('language', normalized);
    this.applyLanguage();
  }

  getCurrentLanguage(): Language {
    return this.normalizeLanguage(localStorage.getItem('language'));
  }

  translate(key: string): string {
    const currentLanguage = this.getCurrentLanguage();
    return this.translations[currentLanguage][key] || this.translations.english[key] || key;
  }

  applyLanguage(): void {
    const language = this.getCurrentLanguage();
    const dir = language === 'urdu' ? 'rtl' : 'ltr';
    const documentLanguage = language === 'english' ? 'en' : language === 'hindi' ? 'hi' : language === 'kannada' ? 'kn' : 'ur';

    document.documentElement.lang = documentLanguage;
    document.documentElement.dir = dir;
    document.body.classList.remove('lang-english', 'lang-kannada', 'lang-hindi', 'lang-urdu');
    document.body.classList.add(`lang-${language}`);
  }
}
